const data = {
  products: [
    {
      name: "Arabica Coffee Scrub",
      category: "Scrubs",
      image: "/images/product1.jpg",
      price: 24,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Arabica COFFEE Body & Face scrub",
      category: "Shirts",
      image: "/images/product2.jpg",
      price: 60,
      brand: "Adidas",
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Love Heals - Lavender Exfoliating Body Scrub",
      category: "Shirts",
      image: "/images/product3.jpg",
      price: 28,
      brand: "Love Heals - Thistle Farms",
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Mostory Grapefruit Body Scrub",
      category: "Scrubs",
      image: "/images/product4.jpg",
      price: 35,
      brand: "Mostory",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Great looking pants",
    },
    {
      name: "Mary Magdalene Body Scrub",
      category: "Scrubs",
      image: "/images/product5.jpg",
      price: 45,
      brand: "Mary Magdalene",
      rating: 5.5,
      numReviews: 5,
      countInStock: 20,
      description: "Most comfortable pants I own.",
    },
  ],
};

export default data;
